class CfgPatches {
    class BLU_C_W {
        units[] = {
            "B_BLUCW_Legionnaire_01",
            "B_BLUCW_SL_01",
            "B_BLUCW_AR_01",
            "B_BLUCW_G_01",
            "B_BLUCW_Medic_01",
            "B_BLUCW_MAT_01",
            "B_BLUCW_EX_01",
			"B_BLUCW_ENG_01",
            "B_BLUCW_Mechanic_01",
            "B_BLUCW_DM_01",
			"B_BLUCW_AMR_01",
            "B_BLUCW_AFV_Crew_01",
            "B_BLUCW_Helicopter_Pilot_01",
			"B_BLUCW_Jet_Pilot_01",
            "B_BLUCW_Helicopter_Crew_01",
            "B_BLUCW_Hellcat_01",
			"B_BLUCW_Hellcat_02",
            "B_BLUCW_M1A2_Abrams_01",
            "B_BLUCW_M1117_ASV_01",
			"B_BLUCW_Jeep_01",
            "B_BLUCW_Trakker_6x6_01",
            "B_BLUCW_Trakker_6x6_Open_01",
            "B_BLUCW_Trakker_Ammo_01",
            "B_BLUCW_Trakker_Fuel_01",
            "B_BLUCW_Trakker_Medical_01",
            "B_BLUCW_Trakker_Repair_01",
            "B_BLUCW_PL_01",
			"B_BLUCW_MMG_01",
			"B_BLUCW_MMGA_01",
			"B_BLUCW_ATGM_01",
			"B_BLUCW_ATGMA_01",
			"B_BLUCW_AA_01",
			"B_BLUCW_AAA_01",
            "B_BLUCW_Radio_Operator_01",
			"B_BLUCW_UAV_Operator_01",
            "B_BLUCW_HMMWV_Unarmed_01",
            "B_BLUCW_HMMWV_M2_01",
			"B_BLUCW_HMMWV_M19_01",
			"B_BLUCW_HMMWV_2d_Open_01",
			"B_BLUCW_HMMWV_2d_Half_Open_01",
			"B_BLUCW_HMMWV_2d_Covered_01",
			"B_BLUCW_HMMWV_4d_Open_01",
			"B_BLUCW_HMMWV_4d_Half_Open_01",
			"B_BLUCW_HMMWV_4d_Covered_01",
			
			//RECON
            "B_BLUCR_Recon_Legionnaire_01",
            "B_BLUCR_Recon_SL_01",
            "B_BLUCR_Recon_AT_Legionnaire_01",
            "B_BLUCR_Recon_Medic_01",
            "B_BLUCR_Recon_Autorifleman_01",
            "B_BLUCR_Recon_Sapper_01",
			"B_BLUCR_Recon_DMarksman_01",
			"B_BLUCR_Prowler_Armed_01",
            "B_BLUCR_Prowler_Unarmed_01",
			"B_BLUCR_Prowler_AT_01",
			"B_BLUCR_M1117_ASV_01",
			"B_BLUCR_MH_6Littlebird_01",
			"B_BLUCR_UH_6Littlebird_Armed_01",
			
			//HELICOPTERS AND PLANES AND SHIT
            "B_BLUCW_UH_8Huron_01",
            "B_BLUCW_UH_8Huron_Unarmed_01",
            "B_BLUCW_AH_99_Blackfoot_01",
			"B_BLUAC_GRIFFON_01",
			"B_BLUAC_BUZZARD_01",
			"B_BLUAC_BUZZARD_02",
			"B_BLUAC_BUZZARD_03",
			"B_BLUCW_Blackhawk_01",
            "B_BLUCW_Pandur_IFV_01",
            "B_BLUCW_Pandur_IFV_Unarmed_01",
            "B_BLUCW_Pandur_IFV_Medical_01",
			"B_BLUCW_Pandur_IFV_02",
			"B_BLUCW_Rhino_01",
			"B_BLUAC_C200_Skyranger_Vehicle_Transport_01",
			"B_BLUAC_AC200_Skyranger_CAS_01",
			"B_BLUAC_C200_Skyranger_Infantry_Transport_01",
			"B_BLUCW_UH_60M_01",
			"B_BLUCW_UH_60_Unarmed_01",
			"B_BLUCW_UH_60_EWS_01",
			"B_BLUCW_UH_60_ESSS_01",
			
			//TURRETS
			"B_BLUCW_Mortar_01_F",
			"B_BLUCW_MK19_TriPod_WD",
			"B_BLUCW_TOW_TriPod_WD",
			"B_BLUCW_M2StaticMG_MiniTripod_WD",
			"B_BLUCW_M2StaticMG_WD",
			"B_BLUCW_static_AA_F",
			"B_BLUCW_static_AT_F",
			
			//AMMO
			"B_BLUCW_Box_corbec_Wps_F",
			"B_BLUCW_Box_corbec_Ammo_F"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "A3_Air_F_EPB_Heli_Light_03",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhsusf_c_m1117",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_02",
            "rhsusf_vehicles",
            "A3_Soft_F_Exp_LSV_01",
            "A3_Air_F_Heli_Heli_Transport_03",
            "A3_Air_F_Beta_Heli_Attack_01"
        };
        author = "Citadel";
        authors[] = { "Citadel" };
    };
};
