//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 170.141838 on Stable branch
// Generated with ALiVE version 1.3.5.1705161
//////////////////////////////////////////////////////////////////////////////////


//////////////////////////////////////////////////////////////////////////////////
//  CLASSNAMES
//////////////////////////////////////////////////////////////////////////////////
/*
Uniforms
Crye Desert - RavPat_TSD_Camo
Crye Woodland - RavPat_TSD_Camo

Helmets
Combat Helmet Desert - RavPatRHS_m97_TSD_desert
Combat Helmet Woodland - RavPatRHS_m97_TSD

Weapons
M16 carryhandle w/ Laser - corb_rhs_weap_m16a4_handle_anpeq15
M16 carryhandle w/ Laser and ACOG- corb_rhs_weap_m16a4_handle_anpeq15_acog
M16 / M203 w/ Laser - corb_rhs_weap_m16a4_handle_M203_anpeq15

Backpacks
Desert Ravpat Kitbag - RavPat_Backpack_Kitbag_des


*/

class CfgFactionClasses {
    class BLU_C_D {
        displayName = "Corbec Legions (Desert)";
        side = 1;
        flag = "ca\Ca_E\data\flag_blufor_co.paa";
        icon = "ca\Ca_E\data\flag_blufor_co.paa";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        
        class BLU_C_D {
            name = "Corbec Legions (Desert)";

            class Infantry {
                name = "Infantry";

                class BLUCD_infantry_rifle_section {
                    name = "Rifle Section (6)";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit2 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit3 {
                        position[] = {-5,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit4 {
                        position[] = {0,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit5 {
                        position[] = {5,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Legionnaire_01";
                    };
                };

                class BLUCD_infantry_rifle_section_02 {
                    name = "Rifle Section (9)";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit4 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit5 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Legionnaire_01";
                    };
                    class Unit6 {
                        position[] = {-20,-20,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_BLUCD_DM_01";
                    };
                    class Unit7 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Legionnaire_01";
                    };
                    class Unit8 {
                        position[] = {-25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Legionnaire_01";
                    };
                };

                class BLUCD_infantry_element {
                    name = "Element";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Legionnaire_01";
                    };
                };

                class BLUCD_infantry_at_element {
                    name = "AT Element";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                };

                class b_BLUCD_infantry_atgm_element {
                    name = "ATGM Element";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_ATGM_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_ATGMA_01";
                    };
                };

                class b_BLUCD_infantry_manpad_element {
                    name = "MANPAD Element";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AA_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AAA_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class BLUCD_motorized_motorized_section {
                    name = "Motorized Section (6)";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit4 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_ENG_01";
                    };
                    class Unit5 {
                        position[] = {-9,-9,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Trakker_6x6_Open_01";
                    };
                };

                class BLUCD_motorized_motorized_section_copy_1 {
                    name = "Motorized Section (9)";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Legionnaire_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Legionnaire_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Trakker_6x6_Open_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Mechanic_01";
                    };
                };

                class b_BLUCD_motorized_motorized_patrol {
                    name = "Motorized Patrol";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_ENG_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_HMMWV_2d_Half_Open_01";
                    };
                };

                class b_BLUCD_motorized_motor_support_section {
                    name = "Motor Support Section";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_support.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {6,-24,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_Trakker_Ammo_01";
                    };
                    class Unit1 {
                        position[] = {-6,-24,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Trakker_Fuel_01";
                    };
                    class Unit2 {
                        position[] = {12,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Trakker_Medical_01";
                    };
                    class Unit3 {
                        position[] = {-12,-30,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Trakker_Repair_01";
                    };
                };

                class b_BLUCD_motorized_motorized_section_heavy {
                    name = "Motorized Patrol (Heavy)";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit4 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_ENG_01";
                    };
                    class Unit5 {
                        position[] = {-9,5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_M1117_ASV_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

                class BLUCD_mechanized_mechanized_section {
                    name = "Mechanized Section";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {7,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Pandur_IFV_01";
                    };
                    class Unit2 {
                        position[] = {-7,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit3 {
                        position[] = {12,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit4 {
                        position[] = {-12,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit5 {
                        position[] = {17,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit6 {
                        position[] = {-17,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Mechanic_01";
                    };
                };

                class b_BLUCD_mechanized_mechanized_section_aa {
                    name = "Mechanized Section (AA)";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_mech_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_SL_01";
                    };
                    class Unit1 {
                        position[] = {-7,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_AR_01";
                    };
                    class Unit2 {
                        position[] = {12,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_G_01";
                    };
                    class Unit3 {
                        position[] = {-12,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Medic_01";
                    };
                    class Unit4 {
                        position[] = {17,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_MAT_01";
                    };
                    class Unit5 {
                        position[] = {-17,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Mechanic_01";
                    };
                    class Unit6 {
                        position[] = {17,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_Pandur_IFV_02";
                    };
                };

            };

            class Armored {
                name = "Armor";

                class b_BLUCD_armored_m1a2_element {
                    name = "M1A2 Phalanx";
                    side = 1;
                    faction = "BLU_C_D";
                    icon = "\A3\ui_f\data\map\markers\nato\b_armor.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_BLUCD_M1A2_Abrams_01";
                    };
                    class Unit1 {
                        position[] = {10,-17,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_BLUCD_M1A2_Abrams_01";
                    };
                    class Unit2 {
                        position[] = {-10,-17,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_BLUCD_M1A2_Abrams_01";
                    };
                };

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {
    class B_Soldier_F;
    class B_Soldier_F_OCimport_01 : B_Soldier_F { scope = 0; class EventHandlers; };
    class B_Soldier_F_OCimport_02 : B_Soldier_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_SL_F;
    class B_Soldier_SL_F_OCimport_01 : B_Soldier_SL_F { scope = 0; class EventHandlers; };
    class B_Soldier_SL_F_OCimport_02 : B_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class B_soldier_AR_F;
    class B_soldier_AR_F_OCimport_01 : B_soldier_AR_F { scope = 0; class EventHandlers; };
    class B_soldier_AR_F_OCimport_02 : B_soldier_AR_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_GL_F;
    class B_Soldier_GL_F_OCimport_01 : B_Soldier_GL_F { scope = 0; class EventHandlers; };
    class B_Soldier_GL_F_OCimport_02 : B_Soldier_GL_F_OCimport_01 { class EventHandlers; };

    class B_medic_F;
    class B_medic_F_OCimport_01 : B_medic_F { scope = 0; class EventHandlers; };
    class B_medic_F_OCimport_02 : B_medic_F_OCimport_01 { class EventHandlers; };

    class B_soldier_LAT_F;
    class B_soldier_LAT_F_OCimport_01 : B_soldier_LAT_F { scope = 0; class EventHandlers; };
    class B_soldier_LAT_F_OCimport_02 : B_soldier_LAT_F_OCimport_01 { class EventHandlers; };

    class B_soldier_exp_F;
    class B_soldier_exp_F_OCimport_01 : B_soldier_exp_F { scope = 0; class EventHandlers; };
    class B_soldier_exp_F_OCimport_02 : B_soldier_exp_F_OCimport_01 { class EventHandlers; };
	
    class B_soldier_repair_F;
    class B_soldier_repair_F_OCimport_01 : B_soldier_repair_F { scope = 0; class EventHandlers; };
    class B_soldier_repair_F_OCimport_02 : B_soldier_repair_F_OCimport_01 { class EventHandlers; };

    class B_soldier_M_F;
    class B_soldier_M_F_OCimport_01 : B_soldier_M_F { scope = 0; class EventHandlers; };
    class B_soldier_M_F_OCimport_02 : B_soldier_M_F_OCimport_01 { class EventHandlers; };

    class B_crew_F;
    class B_crew_F_OCimport_01 : B_crew_F { scope = 0; class EventHandlers; };
    class B_crew_F_OCimport_02 : B_crew_F_OCimport_01 { class EventHandlers; };

    class B_Helipilot_F;
    class B_Helipilot_F_OCimport_01 : B_Helipilot_F { scope = 0; class EventHandlers; };
    class B_Helipilot_F_OCimport_02 : B_Helipilot_F_OCimport_01 { class EventHandlers; };

    class I_Heli_light_03_dynamicLoadout_F;
    class I_Heli_light_03_dynamicLoadout_F_OCimport_01 : I_Heli_light_03_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class I_Heli_light_03_dynamicLoadout_F_OCimport_02 : I_Heli_light_03_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class rhsusf_m1a2sep1d_usarmy;
    class rhsusf_m1a2sep1d_usarmy_OCimport_01 : rhsusf_m1a2sep1d_usarmy { scope = 0; class EventHandlers; class Turrets; };
    class rhsusf_m1a2sep1d_usarmy_OCimport_02 : rhsusf_m1a2sep1d_usarmy_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

	
    class rhsusf_M1117_D;
    class rhsusf_M1117_D_OCimport_01 : rhsusf_M1117_D { scope = 0; class EventHandlers; class Turrets; };
    class rhsusf_M1117_D_OCimport_02 : rhsusf_M1117_D_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class MainTurret_Out;
            class MainTurret2_Out;
        };
    };

    class iveco_Truck_02_covered_F_D;
    class iveco_Truck_02_covered_F_D_OCimport_01 : iveco_Truck_02_covered_F_D { scope = 0; class EventHandlers; class Turrets; };
    class iveco_Truck_02_covered_F_D_OCimport_02 : iveco_Truck_02_covered_F_D_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class iveco_Truck_02_transport_F_D;
    class iveco_Truck_02_transport_F_D_OCimport_01 : iveco_Truck_02_transport_F_D { scope = 0; class EventHandlers; class Turrets; };
    class iveco_Truck_02_transport_F_D_OCimport_02 : iveco_Truck_02_transport_F_D_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class iveco_Truck_02_ammo_F_D;
    class iveco_Truck_02_ammo_F_D_OCimport_01 : iveco_Truck_02_ammo_F_D { scope = 0; class EventHandlers; };
    class iveco_Truck_02_ammo_F_D_OCimport_02 : iveco_Truck_02_ammo_F_D_OCimport_01 { scope = 0; class EventHandlers; };

    class iveco_Truck_02_fuel_F_D;
    class iveco_Truck_02_fuel_F_D_OCimport_01 : iveco_Truck_02_fuel_F_D { scope = 0; class EventHandlers; };
    class iveco_Truck_02_fuel_F_D_OCimport_02 : iveco_Truck_02_fuel_F_D_OCimport_01 { scope = 0; class EventHandlers; };

    class iveco_Truck_02_medical_F_D;
    class iveco_Truck_02_medical_F_D_OCimport_01 : iveco_Truck_02_medical_F_D { scope = 0; class EventHandlers; };
    class iveco_Truck_02_medical_F_D_OCimport_02 : iveco_Truck_02_medical_F_D_OCimport_01 { scope = 0; class EventHandlers; };

    class iveco_Truck_02_box_F_D;
    class iveco_Truck_02_box_F_D_OCimport_01 : iveco_Truck_02_box_F_D { scope = 0; class EventHandlers; };
    class iveco_Truck_02_box_F_D_OCimport_02 : iveco_Truck_02_box_F_D_OCimport_01 { scope = 0; class EventHandlers; };

    class B_officer_F;
    class B_officer_F_OCimport_01 : B_officer_F { scope = 0; class EventHandlers; };
    class B_officer_F_OCimport_02 : B_officer_F_OCimport_01 { class EventHandlers; };

    class rhsusf_m1025_d;
    class rhsusf_m1025_d_OCimport_01 : rhsusf_m1025_d { scope = 0; class EventHandlers; class Turrets; };
    class rhsusf_m1025_d_OCimport_02 : rhsusf_m1025_d_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class rhsusf_m1025_d_m2;
    class rhsusf_m1025_d_m2_OCimport_01 : rhsusf_m1025_d_m2 { scope = 0; class EventHandlers; class Turrets; };
    class rhsusf_m1025_d_m2_OCimport_02 : rhsusf_m1025_d_m2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class M2_Turret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class B_recon_F;
    class B_recon_F_OCimport_01 : B_recon_F { scope = 0; class EventHandlers; };
    class B_recon_F_OCimport_02 : B_recon_F_OCimport_01 { class EventHandlers; };

    class B_recon_TL_F;
    class B_recon_TL_F_OCimport_01 : B_recon_TL_F { scope = 0; class EventHandlers; };
    class B_recon_TL_F_OCimport_02 : B_recon_TL_F_OCimport_01 { class EventHandlers; };

    class B_T_LSV_01_armed_F;
    class B_T_LSV_01_armed_F_OCimport_01 : B_T_LSV_01_armed_F { scope = 0; class EventHandlers; class Turrets; };
    class B_T_LSV_01_armed_F_OCimport_02 : B_T_LSV_01_armed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopTurret;
            class CodRiverTurret;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class B_recon_LAT_F;
    class B_recon_LAT_F_OCimport_01 : B_recon_LAT_F { scope = 0; class EventHandlers; };
    class B_recon_LAT_F_OCimport_02 : B_recon_LAT_F_OCimport_01 { class EventHandlers; };

    class B_recon_medic_F;
    class B_recon_medic_F_OCimport_01 : B_recon_medic_F { scope = 0; class EventHandlers; };
    class B_recon_medic_F_OCimport_02 : B_recon_medic_F_OCimport_01 { class EventHandlers; };

    class B_recon_exp_F;
    class B_recon_exp_F_OCimport_01 : B_recon_exp_F { scope = 0; class EventHandlers; };
    class B_recon_exp_F_OCimport_02 : B_recon_exp_F_OCimport_01 { class EventHandlers; };

    class B_T_LSV_01_unarmed_F;
    class B_T_LSV_01_unarmed_F_OCimport_01 : B_T_LSV_01_unarmed_F { scope = 0; class EventHandlers; class Turrets; };
    class B_T_LSV_01_unarmed_F_OCimport_02 : B_T_LSV_01_unarmed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_01;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class B_Heli_Transport_03_F;
    class B_Heli_Transport_03_F_OCimport_01 : B_Heli_Transport_03_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Heli_Transport_03_F_OCimport_02 : B_Heli_Transport_03_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class B_Heli_Transport_03_unarmed_F;
    class B_Heli_Transport_03_unarmed_F_OCimport_01 : B_Heli_Transport_03_unarmed_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Heli_Transport_03_unarmed_F_OCimport_02 : B_Heli_Transport_03_unarmed_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class B_Heli_Attack_01_dynamicLoadout_F;
    class B_Heli_Attack_01_dynamicLoadout_F_OCimport_01 : B_Heli_Attack_01_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class B_Heli_Attack_01_dynamicLoadout_F_OCimport_02 : B_Heli_Attack_01_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class O_Heli_Attack_02_dynamicLoadout_F;
    class O_Heli_Attack_02_dynamicLoadout_F_OCimport_01 : O_Heli_Attack_02_dynamicLoadout_F { scope = 0; class EventHandlers; class Turrets; };
    class O_Heli_Attack_02_dynamicLoadout_F_OCimport_02 : O_Heli_Attack_02_dynamicLoadout_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };
	
	class I_C_Offroad_02_unarmed_F;
	
/* ////////////////////////////////////////////////////////////
//  BACKPACKS
////////////////////////////////////////////////////////////
	
    class RavPat_Backpack_Kitbag_des;
    class RavPat_Backpack_Kitbag_des_Medic: RavPat_Backpack_Kitbag_des
	{
		scope=1;
		class TransportItems
		{
			class Medikit
			{
				count=1;
				name="Medikit";
			};
		};
		displayName="[RT] RavPat Kitbag (Medic)";
	};
	
	class TAC_BP_Butt2_OD;
	class TAC_BP_Butt2_OD_Explosive: TAC_BP_Butt2_OD
	{
		scope=1;
		class TransportItems
		{
			class DemoCharge_Remote_Mag
			{
				count=2;
				name="DemoCharge_Remote_Mag";
			};
			class ClaymoreDirectionalMine_Remote_Mag
			{
				count=2;
				name="ClaymoreDirectionalMine_Remote_Mag";
			};
		};
	};
	
	class RavPat_Backpack_Kitbag_des_Explosive: RavPat_Backpack_Kitbag_des
	{
		scope=1;
		class TransportItems
		{
			class DemoCharge_Remote_Mag
			{
				count=3;
				name="DemoCharge_Remote_Mag";
			};
			class ClaymoreDirectionalMine_Remote_Mag
			{
				count=4;
				name="ClaymoreDirectionalMine_Remote_Mag";
			};
			class ATMine_Range_Mag
			{
				count=1;
				name="ATMine_Range_Mag";
			};
		};
	};
	
	class RavPat_Backpack_Kitbag_des_Repair: RavPat_Backpack_Kitbag_des
	{
		scope=1;
		class TransportItems
		{
			class ToolKit
			{
				count=1;
				name="ToolKit";
			};
			class ACE_wirecutter
			{
				count=1;
				name="ACE_wirecutter";
			};
		};
	};

	class RavPat_Backpack_Kitbag_des_MAT: RavPat_Backpack_Kitbag_des
	{
		scope=1;
		class TransportItems
		{
			class tf47_m3maaws_HEDP
			{
				count=2;
				name="tf47_m3maaws_HEDP";
			};
		};
	};
	
	class TAC_BP_Butt2_OD_Grenadier: TAC_BP_Butt2_OD
	{
		scope=1;
		class TransportItems
		{
			class rhs_mag_M397_HET
			{
				count=3;
				name="rhs_mag_M397_HET";
			};
			class rhs_mag_M441_HE
			{
				count=3;
				name="rhs_mag_M441_HE";
			};
			class rhs_mag_m4009
			{
				count=2;
				name="rhs_mag_m4009";
			};
			class rhs_mag_M585_white
			{
				count=1;
				name="rhs_mag_M585_white";
			};
			class rhs_mag_m661_green
			{
				count=1;
				name="rhs_mag_m661_green";
			};
			class rhs_mag_m713_Red
			{
				count=2;
				name="rhs_mag_m713_Red";
			};
			class rhs_mag_M433_HEDP
			{
				count=3;
				name="rhs_mag_M433_HEDP";
			};
		};
	}; */
	
////////////////////////////////////////////////////////////
//  INFANTRY
////////////////////////////////////////////////////////////

	
	class B_BLUCW_Legionnaire_01;
	class B_BLUCW_PL_01;
	class B_BLUCW_SL_01;
	class B_BLUCW_AR_01;
	class B_BLUCW_Radio_Operator_01;
	class B_BLUCW_G_01;
	class B_BLUCW_Medic_01;
	class B_BLUCW_MAT_01;
	class B_BLUCW_EX_01;
	class B_BLUCW_ENG_01;
	class B_BLUCW_DM_01;
	class B_BLUCW_Mechanic_01;
	class B_BLUCW_AFV_Crew_01;
	class B_BLUCW_Helicopter_Pilot_01;
	class B_BLUCW_Helicopter_Crew_01;	
	class B_BLUCW_UAV_Operator_01;
	class B_BLUCW_MMG_01;
	class B_BLUCW_MMGA_01;
	class B_BLUCW_ATGM_01;
	class B_BLUCW_ATGMA_01;
	class B_BLUCW_AA_01;
	class B_BLUCW_AAA_01;
	class B_BLUCW_AMR_01;

	
	
	
    class B_blucd_Legionnaire_01 : B_BLUCW_Legionnaire_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };

    class B_blucd_PL_01 : B_BLUCW_PL_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };

    class B_blucd_SL_01 : B_BLUCW_SL_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };

    class B_blucd_AR_01 : B_BLUCW_AR_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };

	class B_BLUCD_MMG_01 : B_BLUCW_MMG_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };
	
	class B_BLUCD_MMGA_01 : B_BLUCW_MMGA_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };
	
	class B_BLUCD_ATGM_01 : B_BLUCW_ATGM_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };
	
	class B_BLUCD_ATGMA_01 : B_BLUCW_ATGMA_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };
	
	class B_BLUCD_AA_01 : B_BLUCW_AA_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };
	
	class B_BLUCD_AAA_01 : B_BLUCW_AAA_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };

    class B_blucd_Radio_Operator_01 : B_BLUCW_Radio_Operator_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
	};
	
    class B_blucd_UAV_Operator_01 : B_BLUCW_UAV_Operator_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"B_UavTerminal",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
	};

    class B_blucd_G_01 : B_BLUCW_G_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};

    };

    class B_blucd_Medic_01 : B_BLUCW_Medic_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };

    class B_blucd_MAT_01 : B_BLUCW_MAT_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };

    class B_blucd_EX_01 : B_BLUCW_EX_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };
	
	class B_blucd_ENG_01 : B_BLUCW_ENG_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };

    class B_blucd_DM_01 : B_BLUCW_DM_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };
	
	class B_BLUCD_AMR_01 : B_BLUCW_AMR_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
    };

	class B_blucd_Mechanic_01 : B_BLUCW_Mechanic_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
		linkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
		respawnlinkedItems[]=
		{
			"ItemMap",
			"ItemCompass",
			"ItemWatch",
			"ItemRadio",
			"rhsusf_ANPVS_14",
			"RavPat_blu4_OGA_OD",
			"RavPatRHS_m97_TSD"
		};
	};

    class B_blucd_AFV_Crew_01 : B_BLUCW_AFV_Crew_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";    
	};
	
    class B_blucd_Helicopter_Pilot_01 : B_BLUCW_Helicopter_Pilot_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";	
    };
		
    class B_blucd_Helicopter_Crew_01 : B_BLUCW_Helicopter_Crew_01 {
        faction = "BLU_C_D";
		uniformClass="RavPat_TSD_Camo";
    };

////////////////////////////////////////////////////////////
//  VEHICLES
////////////////////////////////////////////////////////////	
	
	class Pandur2_unarmed_D;
    class B_BLUCD_Pandur_IFV_Unarmed_01 : Pandur2_unarmed_D {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pandur IFV (Unarmed)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_BLUCD_AFV_Crew_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

    };

	class Pandur2_medical_D;
    class B_BLUCD_Pandur_IFV_Medical_01 : Pandur2_medical_D {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pandur IFV (Medical)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_BLUCD_AFV_Crew_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};
    };

	class Pandur2_D;
    class B_BLUCD_Pandur_IFV_01 : Pandur2_D {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pandur IFV";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_BLUCD_AFV_Crew_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};
		
		typicalCargo[]=
		{
			"B_BLUCD_AFV_Crew_01"
		};

    };
	
	class Pandur2_AA_D;
    class B_BLUCD_Pandur_IFV_02 : Pandur2_AA_D {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pandur IFV (AA)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_BLUCD_AFV_Crew_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};
		
		typicalCargo[]=
		{
			"B_BLUCD_AFV_Crew_01"
		};

    };


	class B_AFV_Wheeled_01_up_cannon_F;
    class B_BLUCD_Rhino_01 : B_AFV_Wheeled_01_up_cannon_F {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_AFV_Crew_01";
		typicalCargo[]=
			{
				"B_blucd_AFV_Crew_01"
			};
    };	
	
	class B_blucd_Jeep_01 : I_C_Offroad_02_unarmed_F {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "M5 Jeep";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";

		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};
	};	
	
    class B_BLUCD_M1A2_Abrams_01 : rhsusf_m1a2sep1d_usarmy_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "M1A2 Abrams";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_AFV_Crew_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_blucd_AFV_Crew_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_blucd_M1117_ASV_01 : rhsusf_M1117_D_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "M1117 ASV";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_blucd_AR_01"; };
            class MainTurret_Out : MainTurret_Out { gunnerType = "B_blucd_Legionnaire_01"; };
            class MainTurret2_Out : MainTurret2_Out { gunnerType = "B_blucd_SL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "olive";

    };

    class B_blucd_Trakker_6x6_01 : iveco_Truck_02_covered_F_D_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Trakker 6x6";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_blucd_Trakker_6x6_Open_01 : iveco_Truck_02_transport_F_D_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Trakker 6x6 Open";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_blucd_Trakker_Ammo_01 : iveco_Truck_02_ammo_F_D_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Trakker Ammo";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_blucd_Trakker_Fuel_01 : iveco_Truck_02_fuel_F_D_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Trakker Fuel";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_blucd_Trakker_Medical_01 : iveco_Truck_02_medical_F_D_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Trakker Medical";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_blucd_Trakker_Repair_01 : iveco_Truck_02_box_F_D_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "Trakker Repair";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_blucd_HMMWV_Unarmed_01 : rhsusf_m1025_d_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "HMMWV (Unarmed)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class B_blucd_HMMWV_M2_01 : rhsusf_m1025_d_m2_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "HMMWV (M2)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class M2_Turret : M2_Turret { gunnerType = "B_blucd_Legionnaire_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

	class rhsusf_m998_d_2dr_halftop;
    class rhsusf_m998_d_2dr_halftop_OCimport_01 : rhsusf_m998_d_2dr_halftop { scope = 0; class EventHandlers; class Turrets; };
    class rhsusf_m998_d_2dr_halftop_OCimport_02 : rhsusf_m998_d_2dr_halftop_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };
    class B_BLUCD_HMMWV_2d_Half_Open_01 : rhsusf_m998_d_2dr_halftop_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "HMMWV (2d/Half Open)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };
	
////////////////////////////////////////////////////////////
//  TURRETS
////////////////////////////////////////////////////////////	
	
	class B_static_AT_F;
    class B_blucd_static_AT_F : B_static_AT_F {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
	};
		
	class B_static_AA_F;
    class B_blucd_static_AA_F : B_static_AA_F {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
	};
		
	class RHS_M2StaticMG_WD;
    class B_blucd_M2StaticMG_WD : RHS_M2StaticMG_WD {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
	};
		
	class RHS_M2StaticMG_MiniTripod_WD;
    class B_blucd_M2StaticMG_MiniTripod_WD : RHS_M2StaticMG_MiniTripod_WD {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
	};
		
	class RHS_TOW_TriPod_WD;
    class B_blucd_TOW_TriPod_WD : RHS_TOW_TriPod_WD {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
	};
		
	class RHS_MK19_TriPod_WD;
    class B_blucd_MK19_TriPod_WD : RHS_MK19_TriPod_WD {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
	};
		
	class B_Mortar_01_F;
    class B_blucd_Mortar_01_F : B_Mortar_01_F {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Legionnaire_01";
	};
		
	
////////////////////////////////////////////////////////////
//  HELICOPTERS
////////////////////////////////////////////////////////////
	
	class B_BLUCW_Hellcat_01;
    class B_blucd_Hellcat_01 : B_BLUCW_Hellcat_01 {
		
        faction = "BLU_C_D";
        crew = "B_BLUCD_Helicopter_Pilot_01";
		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"RavPat\data\desHell.paa"
		};
    };

	class B_BLUCW_Hellcat_02;
    class B_BLUCD_Hellcat_02 : B_BLUCW_Hellcat_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-4 Hellcat (Unarmed)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_BLUCD_Helicopter_Pilot_01";
		ace_hellfire_addLaserDesignator = 1;
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};
		

		hiddenSelections[]=
		{
			"camo"
		};
		hiddenSelectionsTextures[]=
		{
			"RavPat\data\desHell.paa"
		};

    };
				
	class B_BLUCW_AH_99_Blackfoot_01;
    class B_blucd_AH_99_Blackfoot_01 : B_BLUCW_AH_99_Blackfoot_01 {
        faction = "BLU_C_D";
        crew = "B_blucd_Helicopter_Pilot_01";
    };

	class RHS_UH60M;
    class RHS_UH60M_OCimport_01 : RHS_UH60M { scope = 0; class EventHandlers; class Turrets; };
    class RHS_UH60M_OCimport_02 : RHS_UH60M_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };
    class B_BLUCD_UH_60M_01 : RHS_UH60M_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_blucd_Helicopter_Pilot_01"; };
            class MainTurret : MainTurret { gunnerType = "B_blucd_Helicopter_Crew_01"; };
            class RightDoorGun : RightDoorGun { gunnerType = "B_blucd_Helicopter_Crew_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

	class RHS_UH60M2;
    class RHS_UH60M2_OCimport_01 : RHS_UH60M2 { scope = 0; class EventHandlers; class Turrets; };
    class RHS_UH60M2_OCimport_02 : RHS_UH60M2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };
    class B_BLUCD_UH_60M_Unarmed_01 : RHS_UH60M2_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_blucd_Helicopter_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

	class RHS_UH60M_ESSS2;
    class RHS_UH60M_ESSS2_OCimport_01 : RHS_UH60M_ESSS2 { scope = 0; class EventHandlers; class Turrets; };
    class RHS_UH60M_ESSS2_OCimport_02 : RHS_UH60M_ESSS2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };
    class B_BLUCD_UH_60M_EWS_01 : RHS_UH60M_ESSS2_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_blucd_Helicopter_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };
	
	class RHS_UH60M_ESSS;
    class RHS_UH60M_ESSS_OCimport_01 : RHS_UH60M_ESSS { scope = 0; class EventHandlers; class Turrets; };
    class RHS_UH60M_ESSS_OCimport_02 : RHS_UH60M_ESSS_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };
    class B_BLUCD_UH_60M_ESSS_01 : RHS_UH60M_ESSS_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-60M ESSS";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_blucd_Helicopter_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };
	
    class B_blucd_UH_8Huron_01 : B_Heli_Transport_03_F_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-8 Huron";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Helicopter_Pilot_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_blucd_Helicopter_Pilot_01"; };
            class MainTurret : MainTurret { gunnerType = "B_blucd_Helicopter_Crew_01"; };
            class RightDoorGun : RightDoorGun { gunnerType = "B_blucd_Helicopter_Crew_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Green";

    };

    class B_blucd_UH_8Huron_Unarmed_01 : B_Heli_Transport_03_unarmed_F_OCimport_02 {
        author = "Citadel";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-8 Huron (Unarmed)";
        side = 1;
        faction = "BLU_C_D";
        crew = "B_blucd_Helicopter_Pilot_01";
		
		class TransportWeapons{};
		class TransportMagazines{};
		class TransportItems{};

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "B_blucd_Helicopter_Pilot_01"; };
            class MainTurret : MainTurret { gunnerType = "B_helicrew_F"; };
            class RightDoorGun : RightDoorGun { gunnerType = "B_helicrew_F"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };


};

	//End