class CfgPatches {
    class BLU_C_D {
        units[] = {
            "B_BLUCD_Legionnaire_01",
            "B_BLUCD_SL_01",
            "B_BLUCD_AR_01",
            "B_BLUCD_G_01",
            "B_BLUCD_Medic_01",
            "B_BLUCD_MAT_01",
            "B_BLUCD_EX_01",
			"B_BLUCA_ENG_01",
            "B_BLUCD_Mechanic_01",
            "B_BLUCD_DM_01",
			"B_BLUCD_AMR_01",
            "B_BLUCD_AFV_Crew_01",
            "B_BLUCD_Helicopter_Pilot_01",
            "B_BLUCD_Helicopter_Crew_01",
            "B_BLUCD_Hellcat_01",
			"B_BLUCD_Hellcat_02",
            "B_BLUCD_M1A2_Abrams_01",
            "B_BLUCD_M1117_ASV_01",
            "B_BLUCD_Trakker_6x6_01",
            "B_BLUCD_Trakker_6x6_Open_01",
            "B_BLUCD_Trakker_Ammo_01",
            "B_BLUCD_Trakker_Fuel_01",
            "B_BLUCD_Trakker_Medical_01",
            "B_BLUCD_Trakker_Repair_01",
            "B_BLUCD_PL_01",
			"B_BLUCD_MMG_01",
			"B_BLUCD_MMGA_01",
			"B_BLUCD_ATGM_01",
			"B_BLUCD_ATGMA_01",
			"B_BLUCD_AA_01",
			"B_BLUCD_AAA_01",
            "B_BLUCD_Radio_Operator_01",
			"B_BLUCD_UAV_Operator_01",
			"B_BLUCD_Jeep_01",
            "B_BLUCD_HMMWV_Unarmed_01",
            "B_BLUCD_HMMWV_M2_01",
			"B_BLUCD_HMMWV_M19_01",
			"B_BLUCD_HMMWV_2d_Open_01",
			"B_BLUCD_HMMWV_2d_Half_Open_01",
			"B_BLUCD_HMMWV_2d_Covered_01",
			"B_BLUCD_HMMWV_4d_Open_01",
			"B_BLUCW_HMMWV_4d_Half_Open_01",
			"B_BLUCW_HMMWV_4d_Covered_01",
            "B_BLUCD_UH_8Huron_01",
            "B_BLUCD_UH_8Huron_Unarmed_01",
            "B_BLUCD_AH_99_Blackfoot_01",
            "B_BLUCD_Pandur_IFV_01",
            "B_BLUCD_Pandur_IFV_Unarmed_01",
            "B_BLUCD_Pandur_IFV_Medical_01",
			"B_BLUCD_Mortar_01_F",
			"B_BLUCD_MK19_TriPod_WD",
			"B_BLUCD_TOW_TriPod_WD",
			"B_BLUCD_M2StaticMG_MiniTripod_WD",
			"B_BLUCD_M2StaticMG_WD",
			"B_BLUCD_static_AA_F",
			"B_BLUCD_static_AT_F",
			"B_BLUCD_UH_60M_01",
			"B_BLUCD_UH_60M_Unarmed_01",
			"B_BLUCD_UH_60M_EWS_01",
			"B_BLUCD_UH_60M_ESSS_01",
			"B_BLUCD_Rhino_01",
			"B_BLUCD_Pandur_IFV_02"
        };
        weapons[] = {};
        requiredVersion = 1.62;
        requiredAddons[] = {
            "A3_Characters_F",
            "A3_Air_F_EPB_Heli_Light_03",
            "rhsusf_c_m1a1",
            "rhsusf_c_m1a2",
            "rhsusf_c_m1117",
            "A3_Soft_F_Beta_Truck_02",
            "A3_Soft_F_Gamma_Truck_02",
            "rhsusf_vehicles",
            "A3_Soft_F_Exp_LSV_01",
            "A3_Air_F_Heli_Heli_Transport_03",
            "A3_Air_F_Beta_Heli_Attack_01"
        };
        author = "Citadel";
        authors[] = { "Citadel" };
    };
};
