//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 188.145285 on Stable branch
// Generated with ALiVE version 1.9.1.1901021
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_CBArmy_WDL {
        displayName = "Raven Tactical Woodland";
        side = 1;
        flag = "";
        icon = "";
        priority = 0;
    };
};

class CfgGroups {
    class WEST {

        class B_CBArmy_WDL {
            name = "Raven Tactical Woodland";

            class Infantry {
                name = "Infantry";

                class b_cbarmy_infantry_section_wdl {
                    name = "Section";
                    side = 1;
                    faction = "B_CBArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "LIEUTENANT";
                        side = 1;
                        vehicle = "B_CBArmy_Squad_Leader_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_CBArmy_Medic_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_CBArmy_Engineer_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_CBArmy_Grenadier2IC_WDL_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Rifleman_AT_WDL_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Marksman_WDL_01";
                    };
                };

                class b_cbarmy_infantry_patrol_wdl {
                    name = "Patrol";
                    side = 1;
                    faction = "B_CBArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_CBArmy_Squad_Leader_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 1;
                        vehicle = "B_CBArmy_Medic_WDL_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Rifleman_WDL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Marksman_WDL_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

                class b_cbarmy_motorized_fennek_qrf_wdl {
                    name = "Fennek QRF";
                    side = 1;
                    faction = "B_CBArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_CBArmy_Fennek_Transport_WDL_01";
                    };
                    class Unit1 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Rifleman_WDL_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Medic_WDL_01";
                    };
                };

                class b_cbarmy_motorized_fennek_hmg_wdl {
                    name = "Fennek HMG";
                    side = 1;
                    faction = "B_CBArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_CBArmy_Fennek_HMG_WDL_01";
                    };
                    class Unit1 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Rifleman_WDL_01";
                    };
                };

                class b_cbarmy_motorized_fennek_gmg_wdl {
                    name = "Fennek GMG";
                    side = 1;
                    faction = "B_CBArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_CBArmy_Fennek_GMG_WDL_01";
                    };
                    class Unit1 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Rifleman_WDL_01";
                    };
                };

                class b_cbarmy_motorized_truck_transport_wdl {
                    name = "Truck Transport";
                    side = 1;
                    faction = "B_CBArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_motor_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_CBArmy_Truck_WDL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_CBArmy_Rifleman_AT_WDL_01";
                    };
                };

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

                class b_cbarmy_air_uh4_lynx_wdl {
                    name = "UH4-Lynx";
                    side = 1;
                    faction = "B_CBArmy_WDL";
                    icon = "\A3\ui_f\data\map\markers\nato\b_air.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_CBArmy_UH_4Lynx_WDL_01";
                    };
                };

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_Soldier_SL_F;
    class B_Soldier_SL_F_OCimport_01 : B_Soldier_SL_F { scope = 0; class EventHandlers; };
    class B_Soldier_SL_F_OCimport_02 : B_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class B_medic_F;
    class B_medic_F_OCimport_01 : B_medic_F { scope = 0; class EventHandlers; };
    class B_medic_F_OCimport_02 : B_medic_F_OCimport_01 { class EventHandlers; };

    class B_engineer_F;
    class B_engineer_F_OCimport_01 : B_engineer_F { scope = 0; class EventHandlers; };
    class B_engineer_F_OCimport_02 : B_engineer_F_OCimport_01 { class EventHandlers; };

    class B_soldier_LAT_F;
    class B_soldier_LAT_F_OCimport_01 : B_soldier_LAT_F { scope = 0; class EventHandlers; };
    class B_soldier_LAT_F_OCimport_02 : B_soldier_LAT_F_OCimport_01 { class EventHandlers; };

    class B_Soldier_GL_F;
    class B_Soldier_GL_F_OCimport_01 : B_Soldier_GL_F { scope = 0; class EventHandlers; };
    class B_Soldier_GL_F_OCimport_02 : B_Soldier_GL_F_OCimport_01 { class EventHandlers; };

    class RT_W_Fennek_HMG;
    class RT_W_Fennek_HMG_OCimport_01 : RT_W_Fennek_HMG { scope = 0; class EventHandlers; class Turrets; };
    class RT_W_Fennek_HMG_OCimport_02 : RT_W_Fennek_HMG_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderTurret;
        };
    };

    class RT_W_Fennek_gmg;
    class RT_W_Fennek_gmg_OCimport_01 : RT_W_Fennek_gmg { scope = 0; class EventHandlers; class Turrets; };
    class RT_W_Fennek_gmg_OCimport_02 : RT_W_Fennek_gmg_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CommanderTurret;
        };
    };

    class RT_W_Fennek;
    class RT_W_Fennek_OCimport_01 : RT_W_Fennek { scope = 0; class EventHandlers; class Turrets; };
    class RT_W_Fennek_OCimport_02 : RT_W_Fennek_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CommanderTurret;
        };
    };

    class RT_W_LYNX;
    class RT_W_LYNX_OCimport_01 : RT_W_LYNX { scope = 0; class EventHandlers; class Turrets; };
    class RT_W_LYNX_OCimport_02 : RT_W_LYNX_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class B_G_Offroad_01_F;
    class B_G_Offroad_01_F_OCimport_01 : B_G_Offroad_01_F { scope = 0; class EventHandlers; class Turrets; };
    class B_G_Offroad_01_F_OCimport_02 : B_G_Offroad_01_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };


    class B_CBArmy_Squad_Leader_WDL_01 : B_Soldier_SL_F_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 1;
        faction = "B_CBArmy_WDL";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "RavPat2_DPM_Camo_Cyre";

        linkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"arifle_TRG21_F","hgun_P07_F","Laserdesignator"};
        respawnWeapons[] = {"arifle_TRG21_F","hgun_P07_F","Laserdesignator"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","Laserbatteries","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","Laserbatteries"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","Laserbatteries","30Rnd_556x45_Stanag","16Rnd_9x21_Mag","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_TRG21_F","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"RavPat2_DPM_Camo_Cyre",{{"FirstAidKit",3},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1},{"Chemlight_green",2,1}}},{"RavPat_blu4_olive",{{"HandGrenade",2,1},{"SmokeShell",3,1},{"30Rnd_556x45_Stanag",8,30},{"16Rnd_9x21_Mag",2,16},{"30Rnd_556x45_Stanag_Tracer_Red",1,30}}},{},"H_HelmetB","G_Combat",{"Laserdesignator","","","",{"Laserbatteries",1},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'RT_sl'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "RT_sl";

    };

    class B_CBArmy_Medic_WDL_01 : B_medic_F_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 1;
        faction = "B_CBArmy_WDL";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "RavPat2_DPM_Camo_Cyre";

        linkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"arifle_TRG21_F","hgun_P07_F","Binocular"};
        respawnWeapons[] = {"arifle_TRG21_F","hgun_P07_F","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        backpack = "B_FieldPack_khk";

        ALiVE_orbatCreator_loadout[] = {{"arifle_TRG21_F","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"RavPat2_DPM_Camo_Cyre",{{"FirstAidKit",4},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1},{"Chemlight_green",2,1}}},{"RavPat_blu4_olive",{{"HandGrenade",2,1},{"SmokeShell",3,1},{"30Rnd_556x45_Stanag",8,30},{"16Rnd_9x21_Mag",2,16},{"30Rnd_556x45_Stanag_Tracer_Red",1,30}}},{"B_FieldPack_khk",{{"Medikit",1},{"FirstAidKit",10},{"SmokeShellOrange",4,1},{"Chemlight_yellow",2,1}}},"H_HelmetB","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'RT_Medic'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "RT_Medic";

    };

    class B_CBArmy_Engineer_WDL_01 : B_engineer_F_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer";
        side = 1;
        faction = "B_CBArmy_WDL";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "RavPat2_DPM_Camo_Cyre";

        linkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"arifle_TRG21_F","hgun_P07_F","Binocular"};
        respawnWeapons[] = {"arifle_TRG21_F","hgun_P07_F","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        backpack = "RavPat_Backpack_Kitbag";

        ALiVE_orbatCreator_loadout[] = {{"arifle_TRG21_F","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"RavPat2_DPM_Camo_Cyre",{{"FirstAidKit",4},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1},{"Chemlight_green",2,1}}},{"RavPat_blu4_olive",{{"HandGrenade",2,1},{"SmokeShell",3,1},{"30Rnd_556x45_Stanag",8,30},{"16Rnd_9x21_Mag",2,16},{"30Rnd_556x45_Stanag_Tracer_Red",1,30}}},{"RavPat_Backpack_Kitbag",{{"ToolKit",1},{"MineDetector",1},{"SatchelCharge_Remote_Mag",1,1},{"DemoCharge_Remote_Mag",2,1}}},"H_HelmetB","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'RT_Engineer'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "RT_Engineer";

    };

    class B_CBArmy_Rifleman_AT_WDL_01 : B_soldier_LAT_F_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman AT";
        side = 1;
        faction = "B_CBArmy_WDL";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "RavPat2_DPM_Camo_Cyre";

        linkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"arifle_TRG21_F","launch_RPG7_F","hgun_P07_F","Rangefinder"};
        respawnWeapons[] = {"arifle_TRG21_F","launch_RPG7_F","hgun_P07_F","Rangefinder"};

        magazines[] = {"30Rnd_556x45_Stanag","RPG7_F","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","RPG7_F","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        backpack = "B_AssaultPack_rgr";

        ALiVE_orbatCreator_loadout[] = {{"arifle_TRG21_F","","","",{"30Rnd_556x45_Stanag",30},{},""},{"launch_RPG7_F","","","",{"RPG7_F",1},{},""},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"RavPat2_DPM_Camo_Cyre",{{"FirstAidKit",4},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1},{"Chemlight_green",2,1}}},{"RavPat_blu4_olive",{{"HandGrenade",2,1},{"SmokeShell",3,1},{"30Rnd_556x45_Stanag",8,30},{"16Rnd_9x21_Mag",2,16},{"30Rnd_556x45_Stanag_Tracer_Red",1,30}}},{"B_AssaultPack_rgr",{{"RPG7_F",4,1}}},"H_HelmetB","G_Tactical_Clear",{"Rangefinder","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'RT_Exp'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "RT_Exp";

    };

    class B_CBArmy_Marksman_WDL_01 : B_CBArmy_Squad_Leader_WDL_01 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 1;
        faction = "B_CBArmy_WDL";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "RavPat2_DPM_Camo_Cyre";

        linkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"RT_vs121olive","hgun_P07_F","Binocular"};
        respawnWeapons[] = {"RT_vs121olive","hgun_P07_F","Binocular"};

        magazines[] = {"10Rnd_762x54_Mag","16Rnd_9x21_Mag","10Rnd_762x54_Mag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"10Rnd_762x54_Mag","16Rnd_9x21_Mag","10Rnd_762x54_Mag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"RT_vs121olive","","","optic_MRCO",{"10Rnd_762x54_Mag",10},{},"bipod_01_F_blk"},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"RavPat2_DPM_Camo_Cyre",{{"FirstAidKit",4},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1},{"Chemlight_green",2,1}}},{"RavPat_blu4_olive",{{"HandGrenade",2,1},{"SmokeShell",3,1},{"16Rnd_9x21_Mag",2,16},{"10Rnd_762x54_Mag",9,10}}},{},"H_HelmetB","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'RT_Snipe'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "RT_Snipe";

    };

    class B_CBArmy_Grenadier2IC_WDL_01 : B_Soldier_GL_F_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier2IC";
        side = 1;
        faction = "B_CBArmy_WDL";

        identityTypes[] = {"Head_NATO","LanguageENG_F","G_NATO_default"};

        uniformClass = "RavPat2_DPM_Camo_Cyre";

        linkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"arifle_TRG21_GL_F","hgun_P07_F","Binocular"};
        respawnWeapons[] = {"arifle_TRG21_GL_F","hgun_P07_F","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        backpack = "B_AssaultPack_khk";

        ALiVE_orbatCreator_loadout[] = {{"arifle_TRG21_GL_F","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"RavPat2_DPM_Camo_Cyre",{{"FirstAidKit",4},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1},{"Chemlight_green",2,1}}},{"RavPat_blu4_olive",{{"HandGrenade",2,1},{"SmokeShell",3,1},{"16Rnd_9x21_Mag",2,16},{"30Rnd_556x45_Stanag",8,30},{"30Rnd_556x45_Stanag_Tracer_Red",1,30}}},{"B_AssaultPack_khk",{{"1Rnd_HE_Grenade_shell",10,1},{"UGL_FlareWhite_F",3,1},{"1Rnd_SmokeRed_Grenade_shell",4,1},{"1Rnd_Smoke_Grenade_shell",8,1},{"MiniGrenade",4,1},{"HandGrenade",2,1}}},"H_HelmetB","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'RT_Exp'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "RT_Exp";

    };

    class B_CBArmy_Fennek_HMG_WDL_01 : RT_W_Fennek_HMG_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Fennek HMG";
        side = 1;
        faction = "B_CBArmy_WDL";
        crew = "B_CBArmy_Rifleman_WDL_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_CBArmy_Rifleman_WDL_01"; };
            class CommanderTurret : CommanderTurret { gunnerType = "B_CBArmy_Squad_Leader_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_CBArmy_Fennek_GMG_WDL_01 : RT_W_Fennek_gmg_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Fennek GMG";
        side = 1;
        faction = "B_CBArmy_WDL";
        crew = "B_CBArmy_Rifleman_WDL_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_CBArmy_Rifleman_WDL_01"; };
            class CommanderTurret : CommanderTurret { gunnerType = "B_CBArmy_Squad_Leader_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_CBArmy_Fennek_Transport_WDL_01 : RT_W_Fennek_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Fennek Transport";
        side = 1;
        faction = "B_CBArmy_WDL";
        crew = "B_CBArmy_Rifleman_WDL_01";

        class Turrets : Turrets {
            class CommanderTurret : CommanderTurret { gunnerType = "B_CBArmy_Squad_Leader_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_CBArmy_Rifleman_WDL_01 : B_CBArmy_Squad_Leader_WDL_01 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "B_CBArmy_WDL";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "RavPat2_DPM_Camo_Cyre";

        linkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};
        respawnlinkedItems[] = {"RavPat_blu4_olive","H_HelmetB","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"};

        weapons[] = {"arifle_TRG21_F","hgun_P07_F","Binocular"};
        respawnWeapons[] = {"arifle_TRG21_F","hgun_P07_F","Binocular"};

        magazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};
        respawnMagazines[] = {"30Rnd_556x45_Stanag","16Rnd_9x21_Mag","30Rnd_556x45_Stanag","16Rnd_9x21_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"arifle_TRG21_F","","","",{"30Rnd_556x45_Stanag",30},{},""},{},{"hgun_P07_F","","","",{"16Rnd_9x21_Mag",16},{},""},{"RavPat2_DPM_Camo_Cyre",{{"FirstAidKit",4},{"SmokeShellGreen",1,1},{"SmokeShellBlue",1,1},{"SmokeShellRed",1,1},{"Chemlight_green",2,1}}},{"RavPat_blu4_olive",{{"HandGrenade",2,1},{"SmokeShell",3,1},{"30Rnd_556x45_Stanag",8,30},{"16Rnd_9x21_Mag",2,16},{"30Rnd_556x45_Stanag_Tracer_Red",1,30}}},{},"H_HelmetB","",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_INDEP"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'RT_Simple'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "RT_Simple";

    };

    class B_CBArmy_UH_4Lynx_WDL_01 : RT_W_LYNX_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "UH-4 Lynx";
        side = 1;
        faction = "B_CBArmy_WDL";
        crew = "B_CBArmy_Rifleman_WDL_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "B_CBArmy_Rifleman_WDL_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "B_CBArmy_Squad_Leader_WDL_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "B_CBArmy_Medic_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class B_CBArmy_Truck_WDL_01 : B_G_Offroad_01_F_OCimport_02 {
        author = "Aco";
        scope = 2;
        scopeCurator = 2;
        displayName = "Truck";
        side = 1;
        faction = "B_CBArmy_WDL";
        crew = "B_CBArmy_Grenadier2IC_WDL_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "B_CBArmy_Rifleman_WDL_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "B_CBArmy_Marksman_WDL_01"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "B_CBArmy_Squad_Leader_WDL_01"; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = "B_CBArmy_Medic_WDL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_09_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Bootcamp\Offroad_01\Data\offroad_01_ext_IG_09_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Guerilla_09";

    };

};